from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from signals import get_llm_score, get_stylometric_score
import uuid
import json
from datetime import datetime

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

LOG_FILE = "audit_log.json"

def write_log(entry):
    try:
        with open(LOG_FILE, "r") as f:
            logs = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        logs = []
    logs.append(entry)
    with open(LOG_FILE, "w") as f:
        json.dump(logs, f, indent=2)

def get_log():
    try:
        with open(LOG_FILE, "r") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return []

def get_confidence_score(llm_score, stylometric_score):
    spread = abs(llm_score - stylometric_score)
    if spread > 0.3:
        return None, True  # force uncertain
    combined = (0.4 * llm_score) + (0.6 * stylometric_score)
    return round(combined, 3), False

def get_label(confidence, forced_uncertain=False):
    if forced_uncertain:
        return "uncertain", "Our system couldn't confidently determine whether this content was AI-generated or human-written. Take this attribution with caution."
    if confidence >= 0.75:
        return "likely_ai", "Our system has determined this content was likely generated by AI with high confidence."
    if confidence >= 0.45:
        return "uncertain", "Our system couldn't confidently determine whether this content was AI-generated or human-written. Take this attribution with caution."
    return "likely_human", "Our system has determined this content was likely written by a human with high confidence."

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()
    text = data.get("text")
    creator_id = data.get("creator_id")
    content_id = str(uuid.uuid4())

    llm_score = get_llm_score(text)
    stylometric_score = get_stylometric_score(text)

    confidence, forced_uncertain = get_confidence_score(llm_score, stylometric_score)
    if forced_uncertain:
        confidence = round((0.4 * llm_score) + (0.6 * stylometric_score), 3)

    attribution, label_text = get_label(confidence, forced_uncertain)

    write_log({
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "llm_score": llm_score,
        "stylometric_score": stylometric_score,
        "confidence": confidence,
        "attribution": attribution,
        "status": "classified"
    })

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylometric_score": stylometric_score,
        "label": label_text
    })

@app.route("/log", methods=["GET"])
def log():
    return jsonify({"entries": get_log()})

@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    content_id = data.get("content_id")
    creator_reasoning = data.get("creator_reasoning")

    try:
        with open(LOG_FILE, "r") as f:
            logs = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return jsonify({"error": "No log found"}), 404

    found = False
    for entry in logs:
        if entry["content_id"] == content_id:
            entry["status"] = "under_review"
            entry["appeal_reasoning"] = creator_reasoning
            entry["appeal_timestamp"] = datetime.utcnow().isoformat() + "Z"
            found = True
            break

    if not found:
        return jsonify({"error": "content_id not found"}), 404

    with open(LOG_FILE, "w") as f:
        json.dump(logs, f, indent=2)

    return jsonify({
        "message": "Appeal received. Your submission is now under review.",
        "content_id": content_id,
        "status": "under_review"
    })

if __name__ == "__main__":
    app.run(debug=True)